### ISSUE TITLE
using different event kinds when publishing

### ISSUE THREAD

**Issue by 1440000bytes** [jeffthibault/python-nostr#1]
> Publish to relays

> from nostr.event import Event
from nostr.relay_manager import RelayManager
from nostr.message_type import ClientMessageType
from nostr.key import generate_private_key, get_public_key

> relay_manager = RelayManager()
relay_manager.add_relay("wss://nostr-pub.wellorder.net")
relay_manager.add_relay("wss://relay.damus.io")
relay_manager.open_connections()

> private_key = generate_private_key()
public_key = get_public_key(private_key)

> event = Event(public_key, "Hello Nostr")
event.sign(private_key)

> message = json.dumps([ClientMessageType.EVENT, event.to_json_object()])
relay_manager.publish_message(message)

I am assuming event type/kind will be 1 using this example. Is it possible to specify a number for event kind using this library?

**Comment by jeffthibault** [comment]
Yes, event kind 1 is the default. You can set a different event kind using the `EventKind` class. 

Example of using kind 0 (set_metadata):

```python
from Event import Event, EventKind

event = Event(public_key, "<content string>", kind=EventKind.SET_METADATA)
```
`EventKind` class: https://github.com/jeffthibault/python-nostr/blob/main/nostr/event.py#L7
