### ISSUE TITLE
TypeError: Event.__init__() missing 1 required positional argument: 'content'

### ISSUE THREAD

**Issue by pleb21** [jeffthibault/python-nostr#107]
I must be missing something basic. When I try to execute the `Publish to relays` part, i'm thrown this error. The code before that runs fine.

To give a brief on what code I'm running, here's the snippet:
```
# Publish to relays

import json 
import ssl
import time
from nostr.event import Event
from nostr.relay_manager import RelayManager
from nostr.message_type import ClientMessageType
from nostr.key import PrivateKey

relay_manager = RelayManager()
relay_manager.add_relay("wss://nostr-pub.wellorder.net")
relay_manager.add_relay("wss://relay.damus.io")
relay_manager.open_connections({"cert_reqs": ssl.CERT_NONE}) # NOTE: This disables ssl certificate verification
time.sleep(1.25) # allow the connections to open

private_key = PrivateKey()

event = Event('Hello, Nostr')

private_key.sign_event(event)

relay_manager.publish_event(event)
time.sleep(1) # allow the messages to send

relay_manager.close_connections()
```

Help please, TIA

**Comment by pleb21** [comment]
> I must be missing something basic. When I try to execute the `Publish to relays` part, i'm thrown this error. The code before that runs fine.
> 
> To give a brief on what code I'm running, here's the snippet:
> 
> ```
> # Publish to relays
> 
> import json 
> import ssl
> import time
> from nostr.event import Event
> from nostr.relay_manager import RelayManager
> from nostr.message_type import ClientMessageType
> from nostr.key import PrivateKey
> 
> relay_manager = RelayManager()
> relay_manager.add_relay("wss://nostr-pub.wellorder.net")
> relay_manager.add_relay("wss://relay.damus.io")
> relay_manager.open_connections({"cert_reqs": ssl.CERT_NONE}) # NOTE: This disables ssl certificate verification
> time.sleep(1.25) # allow the connections to open
> 
> private_key = PrivateKey()
> 
> event = Event('Hello, Nostr')
> 
> private_key.sign_event(event)
> 
> relay_manager.publish_event(event)
> time.sleep(1) # allow the messages to send
> 
> relay_manager.close_connections()
> ```
> 
> Help please, TIA

Ok, after some hit and trial, here's what I did and it seems to be working.
I added the 2 arguments(public key & content) to the `event` initialization as follows:
`event = Event(private_key.public_key.hex(), 'Hello Nostr world')`

I clearly don't know what I'm doing but for now it seems to work. 
Would love if someone could help me out for better understanding.

**Comment by pleb21** [comment]
I'm just wondering, shouldn't this issue be open. As in, the `event` instance needs to be provided with the public key & content. Or am I missing something here?

**Comment by Jxck-S** [comment]
I don't see the error thrown, did you forget to add it to your post?

**Comment by pleb21** [comment]
the title is the error thrown when I try to publish a note. specifically `event = Event('Hello, Nostr')`

After a few trials, I came to the conclusion that if I modify the call to `event = Event(pub_hex, 'Hello Nostr')`, it works fine. My understanding is that I need to pass both the public key and content as parameters. In other words, passing just the content throws that error.

**Comment by franzos** [comment]
@pleb21 you're right, looks like the docs are outdated. Here's what I got from pip (v0.0.2)

```python
class Event():
    def __init__(
            self, 
            public_key: str,            # required
            content: str,               # required
            created_at: int = None, 
            kind: int=EventKind.TEXT_NOTE, 
            tags: "list[list[str]]"=[], 
            id: str=None, 
            signature: str=None) -> None:
        if not isinstance(content, str):
            raise TypeError("Argument 'content' must be of type str")

        self.public_key = public_key
        self.content = content
        self.created_at = created_at or int(time.time())
        self.kind = kind
        self.tags = tags
        self.signature = signature
        self.id = id or Event.compute_id(self.public_key, self.created_at, self.kind, self.tags, self.content)

...
```

**Comment by pleb21** [comment]
> @pleb21 you're right, looks like the docs are outdated. Here's what I got from pip (v0.0.2)
> 
> ```python
> class Event():
>     def __init__(
>             self, 
>             public_key: str,            # required
>             content: str,               # required
>             created_at: int = None, 
>             kind: int=EventKind.TEXT_NOTE, 
>             tags: "list[list[str]]"=[], 
>             id: str=None, 
>             signature: str=None) -> None:
>         if not isinstance(content, str):
>             raise TypeError("Argument 'content' must be of type str")
> 
>         self.public_key = public_key
>         self.content = content
>         self.created_at = created_at or int(time.time())
>         self.kind = kind
>         self.tags = tags
>         self.signature = signature
>         self.id = id or Event.compute_id(self.public_key, self.created_at, self.kind, self.tags, self.content)
> 
> ...
> ```

@franzos Right, thanks -- I figured as much. btw, how do I get that response (as in, what do I have to type on my terminal? sorry, n00b here and just use `pip` to install stuff, like `pip install nostr` in this case).

**Comment by franzos** [comment]
@pleb21 not sure I follow. Do you mean this: https://github.com/nostr-protocol/nips/blob/master/20.md? 

> When submitting events to relays, clients currently have no way to know if an event was successfully committed to the database. This NIP introduces the concept of command results which are like NOTICE's except provide more information about if an event was accepted or rejected.

**Comment by pleb21** [comment]
> @pleb21 not sure I follow. Do you mean this: https://github.com/nostr-protocol/nips/blob/master/20.md?
> 
> > When submitting events to relays, clients currently have no way to know if an event was successfully committed to the database. This NIP introduces the concept of command results which are like NOTICE's except provide more information about if an event was accepted or rejected.

oh no, sorry for the confusion(a true n00b).
I just meant to ask how did you get the output that you pasted in your previous response which had the `# required` comment in the output. It's not important, but just wanted to know where did you find this code(below):
```
class Event():
    def __init__(
            self, 
            public_key: str,            # required
            content: str,               # required
            created_at: int = None, 
            kind: int=EventKind.TEXT_NOTE, 
            tags: "list[list[str]]"=[], 
            id: str=None, 
            signature: str=None) -> None:
        if not isinstance(content, str):
            raise TypeError("Argument 'content' must be of type str")

        self.public_key = public_key
        self.content = content
        self.created_at = created_at or int(time.time())
        self.kind = kind
        self.tags = tags
        self.signature = signature
        self.id = id or Event.compute_id(self.public_key, self.created_at, self.kind, self.tags, self.content)
```

**Comment by franzos** [comment]
@pleb21 the code can be found here https://github.com/jeffthibault/python-nostr/blob/8eda01180cd0227f86f4d2b3316ac2d2500a53a9/nostr/event.py#L19C15-L19C15 (`v0.0.2`). You can see that it differs from the code on the `master` branch https://github.com/jeffthibault/python-nostr/blob/main/nostr/event.py#L25.

PS: If your original question has been resolved, please close the issue.
