### ISSUE TITLE
Is this project not being updated?

### ISSUE THREAD

**Issue by AaruBama** [jeffthibault/python-nostr#111]
I recently came across this project and last PR seems to have merged many months back with multiple open Issues.
If this project is being maintained, please let us know in 3 days.

Otherwise, I'll fork the project and start building on top of it.
Thanks.

**Comment by afeezaziz** [comment]
It has been more than three days. Wheres your fork?

**Comment by AaruBama** [comment]
It's still on my local. :laughing: Haven't had the time to create a PR and push.
my major concern was relays not responding so I added some more logs and retries. That's all i have done. I'm back to my other project for now so the python-nostr implementation is not something I'm working on so actively.

**Comment by AaruBama** [comment]
Closing because it's been 3 weeks since this issue was created and there is no revert so far. I think the i've the answer and that marks the issue done from my side.

**Comment by afeezaziz** [comment]
If you dont publish the fork, then its not a real fork....but up to you.
