### ISSUE TITLE
Creating a Release

### ISSUE THREAD

**Issue by k9ert** [jeffthibault/python-nostr#15]
I'd like to see a release for this repo and i'm happy to contribute for that. The "nostr" project-name is already [taken](https://pypi.org/project/nostr/) but the [owner](https://twitter.com/brunn3is/status/1608085974453735425) is happy to pass it over. I've volunteered to coordinate the first release and i'm happy to pass the ownership over as soon as you would like to have it (or @labteral  / @/brunneis is passing it over directly).

**Comment by k9ert** [comment]
I've created a proposal on how to do initial releasing in #16

**Comment by jeffthibault** [comment]
@k9ert ACK on creating a release, will review your proposal soon.

@brunneis thanks, I have created an account: https://pypi.org/user/jeffthibault/

**Comment by k9ert** [comment]
Fixed!
