### ISSUE TITLE
Additional conversion class methods for PublicKey, PrivateKey

### ISSUE THREAD

**Issue by armstrys** [jeffthibault/python-nostr#17]
Was really glad to see that support for `PrivateKey.from_nsec()`. It would also be helpful to have a `PublicKey.from_npub()` and possibly a `.from_hex()` method for each since, for example, clients need to decode public keys in text to create tags. 

I’ve experimented a bit with having a base `Key` class that carries some of these generic methods. It works quite well, but does require renaming `PrivateKey.raw_secret` to `PrivateKey.raw_bytes` and I’m not sure if that would be acceptable from a design standpoint.

**Comment by jeffthibault** [comment]
`PublicKey.from_npub()` added in #22
