### ISSUE TITLE
WebSocketConnectionClosedException error when trying publish example

### ISSUE THREAD

**Issue by 1440000bytes** [jeffthibault/python-nostr#2]
```
Traceback (most recent call last):
  File "/home/test/Downloads/python-nostr/str1.py", line 19, in <module>
    relay_manager.publish_message(message)
  File "/home/test/Downloads/python-nostr/nostr/relay_manager.py", line 42, in publish_message
    relay.publish(message)
  File "/home/test/Downloads/python-nostr/nostr/relay.py", line 47, in publish
    self.ws.send(message)
  File "/home/test/.local/lib/python3.10/site-packages/websocket/_app.py", line 203, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/home/test/.local/lib/python3.10/site-packages/websocket/_core.py", line 278, in send
    return self.send_frame(frame)
  File "/home/test/.local/lib/python3.10/site-packages/websocket/_core.py", line 306, in send_frame
    l = self._send(data)
  File "/home/test/.local/lib/python3.10/site-packages/websocket/_core.py", line 520, in _send
    return send(self.sock, data)
  File "/home/test/.local/lib/python3.10/site-packages/websocket/_socket.py", line 143, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by jeffthibault** [comment]
I think this is a thread timing issue. Try adding a sleep after opening the relay connections.

```python
relay_manager.open_connections()
time.sleep(1.25)
```

**Comment by 1440000bytes** [comment]
> I think this is a thread timing issue. Try adding a sleep after opening the relay connections.
> 
> ```python
> relay_manager.open_connections()
> time.sleep(1.25)
> ```

This did not work

**Comment by jeffthibault** [comment]
Okay, I think you need to add the `ssl_options` argument to `open_connections`.

```python
relay_manager.open_connections({"cert_reqs": ssl.CERT_NONE})
time.sleep(1.25)
```
I still need to get a better understanding of how the certificate verification works so I can handle it better but this is working for me.

I also need to add better error handling 😆 

Docs for underlying websocket library: https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-disable-ssl-cert-verification

**Comment by 1440000bytes** [comment]
I thinks it works with just `sleep` and no ssl but how do I print the event id of the published event?

**Comment by jeffthibault** [comment]
After you create the event, you can do `print(event.id)`

Also, at the end, you can add `relay_manager.close_connections()` to close the websocket connections instead of using ctrl-c.

**Comment by leffw** [comment]
> After you create the event, you can do `print(event.id)`
> 
> Also, at the end, you can add `relay_manager.close_connections()` to close the websocket connections instead of using ctrl-c.

I'm getting the same error, try what was mentioned above and the error still persists.

**Comment by 1440000bytes** [comment]
@leffw have you tried changing sleep time?
