### ISSUE TITLE
bug: publishing message as dictionary instead of string 

### ISSUE THREAD

**Issue by 1440000bytes** [jeffthibault/python-nostr#3]
Publishing content as dictionary instead of string returns event id but no event is found when checking relay events.

Use `wss://relay.nostr.info` relay with this snippet to publish this json in the README example to reproduce:

```python
data = {}
data['txid'] = "2cd2821390126c5407f29be8669c612a4092d0bc11224811a0752ff7fa31d43a"
data['vout'] = '1'
data['descriptor'] = "wpkh([ed9062ee/84'/1'/0'/0/0]0261dffbc33896fa21168d72fb74c80ca6af133c638b86e5e8a08645dbd752dca4)#gqkw68za"
data['type'] = 'input'

event = Event(public_key, data, kind=90)
```

It will return an event id but there would be no event with kind=90 for that relay.

Sending string instead of dict would fix this:

```diff
-event = Event(public_key, data, kind=90)
+event = Event(public_key, str(data), kind=90)
```

I understand content is `str` in Event class however sending other type should have either resulted in an error or converted to string or at least does not return event id.

**Comment by jeffthibault** [comment]
Yeah, I still need to add some type validation, especially for the Event class. I will work on that.
