### ISSUE TITLE
[question] what is subscription_id 

### ISSUE THREAD

**Issue by mat-l** [jeffthibault/python-nostr#43]
Thank you for the nostr python packages. I was able to quickly publish notes to my own nostr relay with your package.

Next steps is to pull notes from my relay. For this In would like to use your published code for receiving events. Here I didn't find any information in the web about the "subscription_id = <a string to identify a subscription>". What am I supposed to use as an subscription id, for example if I would like to pull the last 10 events from my relay?

Best regards

**Comment by jeffthibault** [comment]
Thanks, I'm glad you find it useful.

Subscription id is just a string to identify the subscription. It can be anything you want such as a random string of letters and numbers ("d5n22qze9") or something more obvious ("my-events").

**Comment by mat-l** [comment]
Works now as well 👍🏽 

For encrypted direct message I need to be a bit patient for the PR, right? https://github.com/jeffthibault/python-nostr/pull/39
Or could I also already send encrypted messages?
