### ISSUE TITLE
Wrong message order/time

### ISSUE THREAD

**Issue by f321x** [jeffthibault/python-nostr#5]
When posting messages quickly one after another the order gets wrong and messages appear earlier than others even though they got sent later
In the screenshot you can see type 4 messages i sent with the module displayed in anigma.io, the 2nd message is actually the newest one but somehow the time is wrong

![Bildschirmfoto vom 2022-10-23 15-54-39](https://user-images.githubusercontent.com/51097237/197397505-a32b07f2-fd7a-4b51-90b4-845294221b14.png)

**Comment by jeffthibault** [comment]
In python-nostr, when you create a new Event object, it sets the `created_at` field to the current unix timestamp by default. Are you explicitly setting the `created_at` time in your code?

Also, does anigma sort the messages after it receives them? I don't think relays guarantee events will be sorted.

**Comment by f321x** [comment]
Yeah I just noticed that relays don't order by the created_at time and simply give a random note when fetching with a limit of 1.
Fetching more notes and sorting them locally helped me with this issue, sorry for not closing earlier.
Also thx for the great module, really helps getting started with nostr.

**Comment by jeffthibault** [comment]
Cool, that was my intention for this module. I'm glad you find it useful 😃
