### ISSUE TITLE
[Question] decrypt_message public_key?

### ISSUE THREAD

**Issue by nbourbon** [jeffthibault/python-nostr#63]
Hi, I was having a look at this repo and when I was testing the Private_Key Class I could not really understand why this class has the public key as parameter?

If I have an object that has a given private_key the only pub_key that would work for that function is private_key.public_key.hex()  so I can't really understand why do we need to manually add the public key there? is there any other use case that I'm missing?

Thanks and congrats for this repo

**Comment by AveragePythonEnjoyer29** [comment]
Nostr uses public-key cryptography as a way of identifying users. 

### Example
When alice generates a keypair, it consists of private key PRIVKEY1 and public key PUBKEY1. Bob also has a keypair, with private key PRIVKEY2 and public key PUBKEY2.

Alice can now lookup Bob using PUBKEY2 (bobs public key) and encrypt messages using **her private key** and **bobs public key**. Bob can then decrypt the message using **his private key** and **alices public key**

Both the encrypt and decrypt function is done with the private key

I wrote a full example in this issue ![here](https://github.com/jeffthibault/python-nostr/issues/56)

**Comment by AveragePythonEnjoyer29** [comment]
If RSA was picked for this project, it would mean Alice would encrypt her message using **Bobs public key** which in turn he can decrypt with **his private key**. If Bob wanted to send a message he would use **Alices public key** to encrypt the message, and then Alice could decrypt it using **her private key**

(assuming the private keys and public keys are generated together)

**Comment by nbourbon** [comment]
Got it. I thought it was using the same encryption logic bitcoin uses where to decrypt something I don’t need to have the senders public key 

but here you first compute a shared secret in a  Diffie Hellman style?

**Comment by AveragePythonEnjoyer29** [comment]
> Got it. I thought it was using the same encryption logic bitcoin uses where to decrypt something I don’t need to have the senders public key
> 
> but here you first compute a shared secret in a Diffie Hellman style?

yes, the shared secret is computed using Elliptic Curve Diffie Hellman (ECDH) using the SECP256K1 curve

**Comment by nbourbon** [comment]
Thanks! It’s clear now.
