### ISSUE TITLE
EncryptedDirectMessage Issue

### ISSUE THREAD

**Issue by augustfr** [jeffthibault/python-nostr#66]
`import json
import ssl
import time
from nostr.key import PrivateKey
from nostr.filter import Filter, Filters
from nostr.event import Event, EventKind, EncryptedDirectMessage
from nostr.relay_manager import RelayManager
from nostr.message_type import ClientMessageType

sharedSecretPrivate = PrivateKey()
sharedSecretPublic = sharedSecretPrivate.public_key

print(f"Private key: {sharedSecretPrivate.bech32()}")
print(f"Public key: {sharedSecretPublic.bech32()}")

relay_manager = RelayManager()
relay_manager.add_relay("wss://nostr-pub.wellorder.net")
relay_manager.add_relay("wss://relay.damus.io")
relay_manager.open_connections({"cert_reqs": ssl.CERT_NONE}) # NOTE: This disables ssl certificate verification
time.sleep(1.25) # allow the connections to open

private_key = PrivateKey()

dm = EncryptedDirectMessage(
  recipient_pubkey=sharedSecretPublic,
  cleartext_content="Secret message!"
)
private_key.sign_event(dm)
relay_manager.publish_event(dm)
time.sleep(1) # allow the messages to send

relay_manager.close_connections()`

When running the above python script, I'm getting this error: 

"Traceback (most recent call last):
  File "/Users/august/Documents/Nostr/nostrtest.py", line 6, in <module>
    from nostr.event import Event, EventKind, EncryptedDirectMessage
ImportError: cannot import name 'EncryptedDirectMessage' from 'nostr.event' (/Users/august/Documents/Nostr/nostrVenv/lib/python3.11/site-packages/nostr/event.py)"

Any ideas?

**Comment by AveragePythonEnjoyer29** [comment]
https://github.com/jeffthibault/python-nostr/issues/65

it's not implemented on the PyPi version yet (the one you installed with pip)
And the github version is the development one (i think)

So we'll have to wait before the new pypi update gets pushed :/

**Comment by augustfr** [comment]
Oh ok got it. Is there a better method for sending an encrypted message with the current version?

**Comment by AveragePythonEnjoyer29** [comment]
are you going to try and talk with other clients or just going to use `python-nostr` for your own project? If so, then you can just implement your own encryption scheme

**Comment by AveragePythonEnjoyer29** [comment]
if you do go down that way, i suggest using the already existing public key cryptography together with XChaCha20Poly1305 (instead of AES-CBC which is the default)

**Comment by augustfr** [comment]
I'm trying to just put together a little system that allows users to create a shared secret, and both use it for posting messages with that only they'll be able to read.

**Comment by AveragePythonEnjoyer29** [comment]
the pypi version has 2 commands avaliable, ![encrypt_message](https://github.com/jeffthibault/python-nostr/blob/main/nostr/key.py#L69) and ![decrypt_message](https://github.com/jeffthibault/python-nostr/blob/main/nostr/key.py#L84). You can use those if you need help
