### ISSUE TITLE
How to convert pubkey to hex

### ISSUE THREAD

**Issue by augustfr** [jeffthibault/python-nostr#67]
I have a pub key generated with sk.public_key, I'm trying to use PrivateKey.encrypt_message but when I run it, I'm getting: ValueError: non-hexadecimal number found in fromhex() arg at position 2

`message = PrivateKey.encrypt_message(sharedSecretPrivate, "Secret message!", sharedSecretPublic)`

**Comment by AveragePythonEnjoyer29** [comment]
the public key has a `.hex()` function, you can use it like this:
```python
public_key = private_key.public_key

print(public_key.hex()
```

the public key class also has a `.bech32()` function incase you want to convert it to that
